spring.application.name = ProgInzSeminar1

# Config for H2 database.
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

# Config for MySQL database.
# While coding the model classes and the database structure is subject to changes, keep it to create-drop. When the DB layer is finished, change it to update.
spring.jpa.hibernate.ddl-auto = create-drop
spring.datasource.url = jdbc:mysql://${MYSQL_HOST:localhost}:3306/minirimi
spring.datasource.username = spring_user
spring.datasource.password = ${db_pass}
spring.datasource.driver-class-name = com.mysql.jdbc.Driver